Repository hms-dbmi/pic-sure-all-in-one, pull requests merged in 2024-02, with the labels that each got.

#113 [ALS-5612] Create Test users with user tokens based on a list of user…
  initial-configuration/jenkins/jenkins-docker/jobs/Automation Test/config.xml
  initial-configuration/jenkins/jenkins-docker/jobs/Create Test Users/config.xml
  initial-configuration/jenkins/jenkins-docker/jobs/Remove Test Users/config.xml
  initial-configuration/jenkins/jenkins-docker/jobs/Run Quality Assurance/config.xml
Labels: enhancement

#115 [ALS-5612] Fix typo and update emails
  initial-configuration/jenkins/jenkins-docker/jobs/Create Test Users/config.xml
  initial-configuration/jenkins/jenkins-docker/jobs/Remove Test Users/config.xml
Labels: bug, ignore-for-release

#116 [ALS-5906] Misc fixes found while doing fresh install
  initial-configuration/install-dependencies.sh
  initial-configuration/jenkins/jenkins-docker/jobs/Configure Institution Node/config.xml
  initial-configuration/jenkins/jenkins-docker/plugins.yml
Labels: bug
