Repository hms-dbmi/pic-sure-all-in-one, pull requests merged in 2024-01, with the labels that each got.

#103 [ALS-5213] Add new job for banner
  initial-configuration/config/httpd/banner_config.json
  initial-configuration/jenkins/jenkins-docker/jobs/Update Banner Configuration/config.xml
  start-picsure.sh
Labels: enhancement

#105 [ALS-0000] bump cb folder
  initial-configuration/jenkins/jenkins-docker/plugins.yml
Labels: ignore-for-release

#106 [ALS-4422] Create root certs in trust store
  initial-configuration/jenkins/jenkins-docker/jobs/Create Root Certs in TrustStore/config.xml
  initial-configuration/jenkins/jenkins-docker/jobs/Initial Configuration Pipeline/config.xml
Labels: bug

#108 Release
  initial-configuration/config/httpd/banner_config.json
  initial-configuration/jenkins/jenkins-docker/jobs/Configure PIC-SURE Token Introspection Token/config.xml
  initial-configuration/jenkins/jenkins-docker/jobs/Create Root Certs in TrustStore/config.xml
  initial-configuration/jenkins/jenkins-docker/jobs/Initial Configuration Pipeline/config.xml
  initial-configuration/jenkins/jenkins-docker/jobs/Update Banner Configuration/config.xml
  initial-configuration/jenkins/jenkins-docker/plugins.yml
  start-jenkins.sh
  start-picsure.sh
Labels: ignore-for-release
